services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - db_redis_data:/var/lib/redis

  db_test:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: app_test
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - 3307:3306
    tmpfs:
      - /var/lib/mysql
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  db_data:
  db_redis_data:
